federation_version: "=2.7.0"
subgraphs:

  api-a:
    routing_url: "http://localhost:8084/graphql"
    schema:
      subgraph_url: "http://localhost:8084/graphql?sdl"

  api-b:
    routing_url: "http://localhost:8086/graphql"
    schema:
      subgraph_url: "http://localhost:8086/graphql?sdl"
